Config to define files to be treated as JSON Schema files
hyperjump-io/json-schema-language-tools pull request #37
Opened 2024-05-11 08:51 UTC by diyaayay

Resolves #5 

Changes:
-The user can now define the files to be watched, the default behavior is to watch all files.

Tested in both VSCode and Neovim.

![image](https://github.com/hyperjump-io/json-schema-language-tools/assets/110971977/a00b942e-e843-4c67-ae6d-83186613414b)

![WhatsApp Image 2024-05-11 at 01 44 33_cae6d68c](https://github.com/hyperjump-io/json-schema-language-tools/assets/110971977/fd74a678-029a-483c-842a-0bd532a9af6a)

2024-05-11 13:51 UTC, jdesrosiers requested changes
I haven't tried yet, but it seem like the initial workspace validation would always use the default patterns. Then during that initial workspace validation, `getDocumentSettings` happens to get called and sets `schemaFilePatterns` to the intended value. Then only the next time there's a change, would the settings would be used. Even if it is somehow getting set properly before first evaluation, we don't want to rely on that side effect.

Another thing that occurred to me is that this is a workspace level config, but the settings are essentially per document. It wouldn't make sense for one document to have a different `schemaFilePatterns` than another. I believe that vscode has a concept of different levels of configs including one on the workspace level and another on the document level. Does anything like that exist on the language server level? I think not, but it's worth checking.

2024-05-11 13:51 UTC, jdesrosiers commented on language-server/src/server.js
> +  ));
The following is my preferred code style for cases like this. I'm surprised the eslint config didn't catch the object literal style and the empty line.

```suggestion
  const matchers = schemaFilePatterns.map((pattern) => {
    return picomatch(pattern, {
      globstar: true,
      matchBase: true,
      dot: true,
      nonegate: true
    });
  });
```

2024-05-11 13:51 UTC, jdesrosiers commented on language-server/src/server.js
> +let schemaFilePatterns = ["**/*.schema.json", "**/schema.json"];
Is it possible to fold this into configuration? I think we can put this into `globalSettings`. Then we should be getting the value only from configuration.

2024-05-12 11:17 UTC, diyaayay commented
> I haven't tried yet, but it seem like the initial workspace validation would always use the default patterns. Then during that initial workspace validation, `getDocumentSettings` happens to get called and sets `schemaFilePatterns` to the intended value. Then only the next time there's a change, would the settings would be used. Even if it is somehow getting set properly before first evaluation, we don't want to rely on that side effect.
> 
> Another thing that occurred to me is that this is a workspace level config, but the settings are essentially per document. It wouldn't make sense for one document to have a different `schemaFilePatterns` than another. I believe that vscode has a concept of different levels of configs including one on the workspace level and another on the document level. Does anything like that exist on the language server level? I think not, but it's worth checking.

Ah yes! I think we need to have the user-defined patterns before the initial validation and that should sort this out. The different level of configs on the language server level is something I've been looking into. I did read into multi-root workspaces with config levels. I'll fix the initial validation bug and then check the workspace level and document level configs.

2024-05-15 15:09 UTC, closed without merging